/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileSetupRouteImport } from './routes/profile-setup'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RentRouteImport } from './routes/rent'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as RoomsIndexRouteImport } from './routes/rooms.index'
import { Route as RoomsIdRouteImport } from './routes/rooms.$id'
import { Route as TenantsIndexRouteImport } from './routes/tenants.index'
import { Route as TenantsIdRouteImport } from './routes/tenants.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RentRoute = RentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIdRoute = RoomsIdRouteImport.update({
  id: '/rooms/$id',
  path: '/rooms/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsIndexRoute = TenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsIdRoute = TenantsIdRouteImport.update({
  id: '/tenants/$id',
  path: '/tenants/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/register': typeof RegisterRoute
  '/rent': typeof RentRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/whatsapp': typeof WhatsappRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/rooms/$id': typeof RoomsIdRoute
  '/tenants/$id': typeof TenantsIdRoute
  '/properties/': typeof PropertiesIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/tenants/': typeof TenantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/register': typeof RegisterRoute
  '/rent': typeof RentRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/whatsapp': typeof WhatsappRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/rooms/$id': typeof RoomsIdRoute
  '/tenants/$id': typeof TenantsIdRoute
  '/properties': typeof PropertiesIndexRoute
  '/rooms': typeof RoomsIndexRoute
  '/tenants': typeof TenantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/register': typeof RegisterRoute
  '/rent': typeof RentRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/whatsapp': typeof WhatsappRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/rooms/$id': typeof RoomsIdRoute
  '/tenants/$id': typeof TenantsIdRoute
  '/properties/': typeof PropertiesIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/tenants/': typeof TenantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/profile-setup'
    | '/register'
    | '/rent'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/whatsapp'
    | '/properties/$id'
    | '/rooms/$id'
    | '/tenants/$id'
    | '/properties/'
    | '/rooms/'
    | '/tenants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/profile-setup'
    | '/register'
    | '/rent'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/whatsapp'
    | '/properties/$id'
    | '/rooms/$id'
    | '/tenants/$id'
    | '/properties'
    | '/rooms'
    | '/tenants'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/profile-setup'
    | '/register'
    | '/rent'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/whatsapp'
    | '/properties/$id'
    | '/rooms/$id'
    | '/tenants/$id'
    | '/properties/'
    | '/rooms/'
    | '/tenants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileSetupRoute: typeof ProfileSetupRoute
  RegisterRoute: typeof RegisterRoute
  RentRoute: typeof RentRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  WhatsappRoute: typeof WhatsappRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
  RoomsIdRoute: typeof RoomsIdRoute
  TenantsIdRoute: typeof TenantsIdRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
  TenantsIndexRoute: typeof TenantsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-setup': {
      id: '/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent': {
      id: '/rent'
      path: '/rent'
      fullPath: '/rent'
      preLoaderRoute: typeof RentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$id': {
      id: '/rooms/$id'
      path: '/rooms/$id'
      fullPath: '/rooms/$id'
      preLoaderRoute: typeof RoomsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/': {
      id: '/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof TenantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/$id': {
      id: '/tenants/$id'
      path: '/tenants/$id'
      fullPath: '/tenants/$id'
      preLoaderRoute: typeof TenantsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileSetupRoute: ProfileSetupRoute,
  RegisterRoute: RegisterRoute,
  RentRoute: RentRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  WhatsappRoute: WhatsappRoute,
  PropertiesIdRoute: PropertiesIdRoute,
  RoomsIdRoute: RoomsIdRoute,
  TenantsIdRoute: TenantsIdRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
  RoomsIndexRoute: RoomsIndexRoute,
  TenantsIndexRoute: TenantsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
